extends Node

enum Style {BASIC, WESLEY, VIKING, COWBOY, ENGLISH, BASEBALL, BEANIE, STRAW, CAP}
enum State {DEFAULT, FISHING, BUILDING, SHOP}
enum Tool {SWORD, AXE, PICKAXE, HOE, WATER, SEED, FISH}
enum Machine {SPRINKLER, FISHER, SCARECROW, DELETE}
enum Craft {BOX, WALL, PYRE}
enum Seed {TOMATO, CORN, PUMPKIN, WHEAT}
enum Item {WOOD, APPLE, TOMATO, CORN, WHEAT, PUMPKIN, FISH, STONE, GOLD}
enum Shop {MAIN, HAT}
enum Visit {SHIP, PYRE}
enum Blob {BLUE, GREEN , RED}
